spring.application.name=EmployeeAPI

# Server
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.net.javaguides=INFO
logging.level.org.springframework.web=INFO
logging.file.name=app.log

# CSV Datei
employee.csv.file=data.csv